modules:
  gravity:
    enabled: false
  auto-messages:
    enabled: true
    messages:
      - '&4&l[ANÚNCIO] &fAtualmente temos &b{online}&f pessoas no servidor!'
      - '&4&l[ANÚNCIO] &fObrigado por jogar em meu servidor, &b{name}&f!'
    delay: 30
